### ISSUE TITLE
Photo grid remove padding from side

### ISSUE THREAD

**Issue by glitchedmob** [Open-SGF/motherhood-reclaimed-website#56]

**Comment by glitchedmob** [comment]
Don't start until #55 has been merged

**Comment by glitchedmob** [comment]
@ethanzitting Noticing some weird stuff here where there's different amounts of padding on either side of this module. Can we just remove that side padding all together so it doesn't conflict with the container class

**Comment by ethanzitting** [comment]
@glitchedmob definitely! I'll get that trimmed off
