### ISSUE TITLE
Responsive Images in Craft

### ISSUE THREAD

**Issue by ethanzitting** [Open-SGF/motherhood-reclaimed-website#63]
find a way to serve the smallest possible image resolution, plus probable javascript fallback for IE11

**Comment by ethanzitting** [comment]
Notes at current point: Look into a plugin that uses image magic (imagic). Get rid of the image transforms in the CMS settings, and carry those out in the twig modules. Consider that the image text callout module allows the image to choose it's width. Better: use srcset in a robust, scalable way to request the right size image from the server. Look at the craft-picture and Retcon plugins for this.

**Comment by ethanzitting** [comment]
For an image upload, we need to have to option to serve a range of resolutions. We may be able to generate these resolutions with a few image transforms in craft and then serve them. Otherwise, we'll want to have a plugin manage it. Craft picture looks promising so far.

**Comment by glitchedmob** [comment]
@ethanzitting does the picture plugin provide it's own field that let's users select multiple images (one for each of the various resolutions) or does it simply just help generate the various transforms and the srcset stuff? I think we should avoid the former. I'd rather have the content admins just select a single image.
